name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 app.py tests/test_app.py

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/vetty-crypto-api.git
        git push heroku main
      env:
        API_KEY: ${{ secrets.API_KEY }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
